// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("ava").default;
var Command$RescriptCli = require("../src/Command.bs.js");

Ava("Tmp", (function (t) {
        var program = Command$RescriptCli.program(function (ctx) {
              ctx.register("", "Help");
              ctx.register("help", "Help");
              ctx.register("help lint", "HelpLint");
              ctx.register("lint", "Lint");
            });
        t.deepEqual(Command$RescriptCli.parse(program, [""]), {
              TAG: "Ok",
              _0: [
                {
                  string: "",
                  parts: [],
                  tag: "Help"
                },
                [""]
              ]
            }, undefined);
        t.deepEqual(Command$RescriptCli.parse(program, ["help"]), {
              TAG: "Ok",
              _0: [
                {
                  string: "help",
                  parts: ["help"],
                  tag: "Help"
                },
                []
              ]
            }, undefined);
        t.deepEqual(Command$RescriptCli.parse(program, ["lint"]), {
              TAG: "Ok",
              _0: [
                {
                  string: "lint",
                  parts: ["lint"],
                  tag: "Lint"
                },
                []
              ]
            }, undefined);
        t.deepEqual(Command$RescriptCli.parse(program, ["help lint"]), {
              TAG: "Ok",
              _0: [
                {
                  string: "help lint",
                  parts: [
                    "help",
                    "lint"
                  ],
                  tag: "HelpLint"
                },
                []
              ]
            }, undefined);
        t.deepEqual(Command$RescriptCli.parse(program, ["lint help"]), {
              TAG: "Ok",
              _0: [
                {
                  string: "lint",
                  parts: ["lint"],
                  tag: "Lint"
                },
                []
              ]
            }, undefined);
        t.deepEqual(Command$RescriptCli.parse(program, ["lins help"]), {
              TAG: "Error",
              _0: undefined
            }, undefined);
      }));

/*  Not a pure module */
