// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("ava").default;
var RescriptCliBuilder = require("../src/RescriptCliBuilder.bs.js");

Ava("Api", (function (t) {
        var builder = RescriptCliBuilder.make(function (ctx) {
              ctx.command("", "Root");
              ctx.command("help", "Help");
              ctx.command("help lint", "HelpLint");
              ctx.command("lint", "Lint");
            });
        t.deepEqual(RescriptCliBuilder.parse(builder, []), {
              TAG: "Ok",
              _0: [
                {
                  string: "",
                  parts: [],
                  tag: "Root"
                },
                []
              ]
            }, undefined);
        t.deepEqual(RescriptCliBuilder.parse(builder, [""]), {
              TAG: "Ok",
              _0: [
                {
                  string: "",
                  parts: [],
                  tag: "Root"
                },
                [""]
              ]
            }, undefined);
        t.deepEqual(RescriptCliBuilder.parse(builder, ["help"]), {
              TAG: "Ok",
              _0: [
                {
                  string: "help",
                  parts: ["help"],
                  tag: "Help"
                },
                []
              ]
            }, undefined);
        t.deepEqual(RescriptCliBuilder.parse(builder, ["lint"]), {
              TAG: "Ok",
              _0: [
                {
                  string: "lint",
                  parts: ["lint"],
                  tag: "Lint"
                },
                []
              ]
            }, undefined);
        t.deepEqual(RescriptCliBuilder.parse(builder, [
                  "help",
                  "lint"
                ]), {
              TAG: "Ok",
              _0: [
                {
                  string: "help lint",
                  parts: [
                    "help",
                    "lint"
                  ],
                  tag: "HelpLint"
                },
                []
              ]
            }, undefined);
        t.deepEqual(RescriptCliBuilder.parse(builder, ["help lint"]), {
              TAG: "Ok",
              _0: [
                {
                  string: "",
                  parts: [],
                  tag: "Root"
                },
                ["help lint"]
              ]
            }, undefined);
        t.deepEqual(RescriptCliBuilder.parse(builder, [
                  "lint",
                  "help"
                ]), {
              TAG: "Ok",
              _0: [
                {
                  string: "lint",
                  parts: ["lint"],
                  tag: "Lint"
                },
                ["help"]
              ]
            }, undefined);
        t.deepEqual(RescriptCliBuilder.parse(builder, ["lint help"]), {
              TAG: "Ok",
              _0: [
                {
                  string: "",
                  parts: [],
                  tag: "Root"
                },
                ["lint help"]
              ]
            }, undefined);
      }));

/*  Not a pure module */
