// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var RescriptCliBuilder = require("../src/RescriptCliBuilder.bs.js");

function build(param) {
  
}

var App = {
  build: build
};

function log(param) {
  
}

var Console = {
  log: log
};

var builder = RescriptCliBuilder.make(function (ctx) {
      ctx.command("version", "version");
      ctx.command("help", "help");
      ctx.command("help build", "helpBuild");
      ctx.command("build", "build");
    });

var match = RescriptCliBuilder.parse(builder, RescriptCliBuilder.getProcessArgs());

exports.App = App;
exports.Console = Console;
exports.builder = builder;
/* builder Not a pure module */
